apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
    - name: todoapp
      image: dtsy/todoapp:3.0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 8000

      readinessProbe:
        httpGet:
          path: /api/readyz/
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3

      livenessProbe:
        httpGet:
          path: /api/healthz/
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 10
        timeoutSeconds: 2
        failureThreshold: 3